language: python

python:
  - "3.8"

services:
  - docker

install:
  - "pip install -r requirements.txt"

before_script:
  - docker-compose -f .devcontainer/docker-compose.yml up --build -d

script:
  - docker-compose -f .devcontainer/docker-compose.yml run app pytest

after_script:
  - docker-compose down
