# Generated by Django 2.2.2 on 2019-06-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryledger',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Inventory ledger'},
        ),
        migrations.AlterModelOptions(
            name='manufacturingledger',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Manufacturing ledger'},
        ),
        migrations.AlterModelOptions(
            name='purchaseledger',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Purchase ledger'},
        ),
        migrations.AlterModelOptions(
            name='salesledger',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Sales ledger'},
        ),
    ]
