# Generated by Django 2.2.4 on 2019-09-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("purchase", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SupplierContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_contacts",
                        to="purchase.Supplier",
                    ),
                ),
            ],
            options={"ordering": ["last_name", "first_name"]},
        )
    ]
