# Generated by Django 2.2 on 2019-04-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("purchase", "0002_auto_20190412_1725")]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        )
    ]
