# Generated by Django 2.2.2 on 2019-06-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaseorderline_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedproduct',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={'ordering': ['product__name']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
    ]
