# Generated by Django 2.2 on 2019-04-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomitem',
            name='bom',
        ),
        migrations.RemoveField(
            model_name='bomitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='BillOfMaterials',
        ),
        migrations.DeleteModel(
            name='BOMItem',
        ),
    ]
