# Generated by Django 2.1.7 on 2019-03-30 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190330_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterials',
            name='id',
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.Product'),
        ),
    ]
