# Generated by Django 2.2 on 2019-04-11 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190411_2313'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
            options={
                'verbose_name_plural': 'Bill of Materials',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='manufacturing.BillOfMaterials')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bom_items', to='inventory.Product')),
            ],
        ),
    ]
