# Generated by Django 2.2.2 on 2019-06-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_billofmaterials_bomitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomitem',
            options={'ordering': ['product__name']},
        ),
    ]
