# Generated by Django 2.2.2 on 2019-06-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorderline_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='salesorderline',
            options={'ordering': ['product__name']},
        ),
        migrations.AlterModelOptions(
            name='soldproduct',
            options={'ordering': ['name']},
        ),
    ]
